apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-gateway
spec:
  replicas: {{ .Values.identityGateway.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: identity-gateway
  template:
    metadata:
      labels:
        app: identity-gateway
    spec:
          # Configuración para acceder a imágenes privadas
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 10 }}

      containers:
      - name: identity-gateway
        image: "{{ .Values.identityGateway.image.repository }}:{{ .Values.identityGateway.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        env:
        {{- range $key, $value := .Values.identityGateway.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}